### PR TITLE
Replace Kaltura with AWS Transcoder

### PR DESCRIPTION
**Pull request by dougmartin**
This PR represents all the stories up to replacing Ruby and upgrading Rails.

NOTE: There is a cucumber timeout error ("unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055) (Selenium::WebDriver::Error::WebDriverError)") for a few of the cucumber tests when trying to log the user in.  The step failure is intermittent and based on my research I believe this is a issue with the driver gemset vs the Firefox version installed from apt and since the gemsets will all be upgraded as part of the Ruby upgrade I'm going to defer fixing this until then.

### CODE REVIEW

**Comment by dougmartin** [comment]
@scytacki Pack some sandwiches before wading into this one

**Comment by dougmartin** [comment]
Ok - this checkpoint represents all the stories closed in PT.

**Comment by scytacki** [comment]
It would be nice if videojs was included as a gem instead of directly in the source. But I only found the 6 month old unlicensed: https://github.com/seanbehan/videojs_rails/issues  
It doesn't seem worth rolling our own gem.

**Comment by scytacki** [comment]
I'm not sure what happened with the commits but there are few files that only have a few changes, but they are showing up as being completely changed.  For example: https://github.com/concord-consortium/video-paper-builder/pull/3/files#diff-9417e290ebbee593241e90d28e1cbf92L1
I'm working my way through it though, you don't need to fix it.

**Comment by scytacki** [comment]
:+1:  Merge at will

**Comment by scytacki** [comment]
I'm not seeing a couple of things (perhaps I'm missing them) in the Schoology commit:
- checking with Schoology to make sure the user is actually in the realm. Otherwise a user could just craft a URL with an allowed realm and they would get access to VPB.
- a login with schoology button that would allow a user to log in without going to Schoology first.

**Comment by dougmartin** [comment]
The schoology login button is a link next to the forgot password button.  I thought it best to keep it downplayed to avoid confusion in the login.

And you are right about checking for the user in the group or class - I forgot about that :(.  I'll add it this morning.

**Comment by scytacki** [comment]
:+1:

**Pull request merged**
